### ISSUE TITLE
Remove temporary files at some point

### ISSUE THREAD

**Issue by lehnerpat** [smetzlaff/openDLX#2]
openDLX creates two temporary files (a `.cfg` and a `.bin`) file for every time code is assembled in the simulator. These files are placed in the global temp directory, as provided by the JVM (which in my case, on Linux, is `/tmp`).

However, these files are never deleted, and thus clutter up the temp folder quite a bit. It would be nice if these could get deleted, for example when assembling (or loading) the next pair of `.bin`/`.cfg` files or when exiting the program.

**Comment by lehnerpat** [comment]
I just noticed that there is already some code for this in `CommandExitProgram`. However, as far as I can tell, this command is only called when the user uses the "Exit" menu item, not if the program is closed by clicking the X button in the window border.

**Comment by smetzlaff** [comment]
Yes, that's right I've forgot about that. On every 'assemble' a new pair of .cfg and .bin is created, but never deleted. I'll take a look at this the next couple of days.

**Comment by smetzlaff** [comment]
I've registered a window close hook to call the same code as `CommandExitProgram`. This fixes this issue.
