### ISSUE TITLE
Wrong execution path

### ISSUE THREAD

**Issue by egrath** [smetzlaff/openDLX#22]
In some situations wrong commands are executed. Example:

```
.global main

main:
    jal subroutine      ; Call "subroutine"
    jal exit            ; Call "exit"

subroutine:
    xor r1,r1,r1        ; R1 <- 0
    addui r1,r1,0x1     ; R1++
    jr r31              ; Rücksprung

exit:
    trap 0
```

This one should increment R1 to 1 when executed. The increment is never performed because the trap 0 gets executed first.

**Comment by lehnerpat** [comment]
The way the simulator behaves here is correct.

![instr-cycles-issue22](https://f.cloud.github.com/assets/1099818/1489720/757e4002-477f-11e3-81dd-bb5bf9ec833d.png)

OpenDLX follows the DLX specification and does into insert pipeline stalls for jumps (this includes subroutine calls `jal`). Therefore, both your `jal` commands are read into the pipeline and executed. The `xor` command is run twice (it is once read in-order, then once after the first `jal` jump), then the second jump is executed and the trap command is read. It progresses through the pipeline normally and ends the program when it hits the WB phase.

Edit: You will have to insert commands (or `nop`s) manually between the jumps to prevent this.

**Comment by smetzlaff** [comment]
nevik is right. You have to consider branch delay slots in for DLX. Via the `Simulator` menu You can change the simulators behaviour, such that forwarding can be de/activated. Also a MIPS compatibility mode, which follows the MIPS specification for forwarding and branch delay slots, is provided. 

To test the effect of different forwarding modes take a look at the https://github.com/smetzlaff/openDLX/blob/master/apps/dlx_apps/test_forwarding.s example. The jal is handled as any other unconditional branch.
