### ISSUE TITLE
Change UI behavior to open/close internal frames

### ISSUE THREAD

**Issue by lehnerpat** [smetzlaff/openDLX#5]
"Internal frames" (windows inside the main window) can currently only be opened _and_ closed via the `Window` menu; the title bar of the frames only contain a maximize/restore button, no close button.

I find this a bit annoying when I actually want to close a frame, since I am used to closing any window with the X button on the window title bar.

I think it would improve the usability of the GUI if the frame behaviour were changed to be closable via an X button in the frame title bar; the menu items in the `Window` menu should consequently only be used to open a window (or, if it is already open, bring it to the foreground). The checkbox in the menu item would no longer be needed (though it could be left there as an additional indicator).

This behavior would be more in line with other applications, making it easier for the user to get along with the UI.

**Comment by smetzlaff** [comment]
I would appreciate that. If I have some time I could look into the frame behaviour.

**Comment by smetzlaff** [comment]
If I've understood your request correctly, this issue is resolved with a329a7b9258cc932aed0c20331c17dd54d3d3e5a.
