### ISSUE TITLE
Change EventCommandLookup methods to take Object argument instead of Integer

### ISSUE THREAD

**Issue by lehnerpat** [smetzlaff/openDLX#9]
The `put()` and `get()` methods of `EventCommandLookup` currently take the `hashCode` argument as an `Integer`. On every call of such a method, the object stored is hashed in the location of the method call, which leads to unnecessary code duplication and hinders readability.

Therefore I suggest changing the method signatures to take an `Object` argument instead of an `Integer` one and do the `hashCode()` call within the method.

If there is some usage of these methods where the stored object is **not** actually hashed there and then, please let me know.

I will make these changes when I get the time (it's just changing the method signatures and then tracking down error messages in Eclipse), but if someone else has the time, they're welcome to do it (that's why I post this as an issue and don't open a PR right away).

**Comment by smetzlaff** [comment]
Done, see 8efff8fb98f12fbd3dab27e99f9758151f0e69f9.

**Comment by lehnerpat** [comment]
:+1:
